spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/autobot
    username: bot
    password: botpw
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always

server:
  port: 8080

app:
  symbol: BTCUSDT
  interval: 1m
  exchange:
    baseUrl: https://api.binance.com
